name: rde2
channels:
  - pytorch
  - mcs07
  - chemdataextractor
  - conda-forge
  - defaults
dependencies:
  - tesseract=4.1.1
  - opencv=4.5
  - pytorch=1.10
  - torchvision=0.11
  - python=3.8
  - numpy=1.23
